### ISSUE TITLE
Error en la carga

### ISSUE THREAD

**Issue by jmcastillejo** [jmarcet/movistar-u7d#23]
Hola! me sale un error en la carga utilizando windows 11:

[2022-03-06 18:25:46] [EPG] [INFO] -------------------------
[2022-03-06 18:25:46] [EPG] [INFO] Movistar U7D - EPG v4.8.2
[2022-03-06 18:25:46] [EPG] [INFO] -------------------------
[2022-03-06 18:25:46] [EPG] [INFO] IPTV address: 192.168.1.128
[2022-03-06 18:25:46] [EPG] [WARNING] Missing channels data! Need to download it. Please be patient...
[2022-03-06 18:25:47] [TVG] [INFO] -------------------------
[2022-03-06 18:25:47] [TVG] [INFO] Movistar U7D - TVG v4.8.2
[2022-03-06 18:25:47] [TVG] [INFO] -------------------------
[2022-03-06 18:25:47] [TVG] [INFO] Descargando configuración del cliente
[2022-03-06 18:25:47] [TVG] [INFO] Descargando perfil del servicio
[2022-03-06 18:25:47] [TVG] [INFO] Descargando parámetros de configuración
Traceback (most recent call last):
  File "C:\Users\jmarc\scoop\persist\python\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\Users\jmarc\scoop\persist\python\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "tv_grab_es_movistartv", line 1471, in <module>
  File "C:\Users\jmarc\scoop\apps\python\current\lib\asyncio\runners.py", line 44, in run
  File "C:\Users\jmarc\scoop\apps\python\current\lib\asyncio\base_events.py", line 641, in run_until_complete
  File "tv_grab_es_movistartv", line 1370, in main
  File "tv_grab_es_movistartv", line 493, in get_service_config
TypeError: 'NoneType' object is not subscriptable
[2022-03-06 18:25:47] [EPG] [ERROR] Waiting 15s before trying to update EPG again [2/5]

Alguna idea? Gracias

**Comment by jmarcet** [comment]
Hmm, eso en principio es porque no le llega el multicast del IPTV al ordenador donde lo ejecutas.

¿Qué router usas? ¿Cómo conectas el ordenador, por wifi o con cable?

**Comment by jmcastillejo** [comment]
tengo un router con OpenWrt conectado directamente al ONT de fibra de DIgi y el PC conectado por cable al router, necesito abrir algun puerto?

**Comment by jmarcet** [comment]
Esto sólo funciona con conexiones de fibra de Movistar. Luego, para la configuración de un router con OpenWRT puedes mirar [aquí](https://bandaancha.eu/foros/configurar-openwrt-movistar-internet-1742525)

**Comment by jmcastillejo** [comment]
Ok Gracias!
