### ISSUE TITLE
TypeError: tostring() got an unexpected keyword argument 'xml_declaration'

### ISSUE THREAD

**Issue by Slennox** [jmarcet/movistar-u7d#24]
No puedo descargar la guía EPG. ¿Alguien más experimentado este error?

```
[2022-03-11 23:56:14] [TVG] [INFO] Generando la guía XMLTV...
[2022-03-11 23:56:14] [TVG] [INFO] XML: Descargando info extendida
Traceback (most recent call last):
  File "/usr/local/bin/tv_grab_es_movistartv", line 1473, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/bin/tv_grab_es_movistartv", line 1408, in main
    guide = ElTr.tostring(xml, encoding="UTF-8", xml_declaration=True)
TypeError: tostring() got an unexpected keyword argument 'xml_declaration'
```

**Comment by Slennox** [comment]
El problema era la versión 3.7 de Python, pese a que se indica en la documentación que estaría soportada. Actualizado a Python 3.9 y problema resuelto.
