### ISSUE TITLE
Error KeyError: 'RES_BASE_URI'

### ISSUE THREAD

**Issue by Juaancu08** [jmarcet/movistar-u7d#32]
Hola, No se nada de programacion y me encuentro con un error en el programa el cual sale la pantalla de comandos y se cierra sola aqui todo lo que sale en la pantalla de comandos.

[2022-06-15 04:47:00] [INI] [INFO] =================
[2022-06-15 04:47:00] [INI] [INFO] Movistar U7D v5.1
[2022-06-15 04:47:00] [INI] [INFO] =================
[2022-06-15 04:47:00] [INI] [INFO] IPTV address: 192.168.1.43
[2022-06-15 04:47:04] [EPG] [INFO] -----------------------
[2022-06-15 04:47:04] [EPG] [INFO] Movistar U7D - EPG v5.1
[2022-06-15 04:47:04] [EPG] [INFO] -----------------------
[2022-06-15 04:47:04] [EPG] [WARNING] Missing channels data! Need to download it. Please be patient...
[2022-06-15 04:47:05] [TVG] [INFO] -----------------------
[2022-06-15 04:47:05] [TVG] [INFO] Movistar U7D - TVG v5.1
[2022-06-15 04:47:05] [TVG] [INFO] -----------------------
[2022-06-15 04:47:05] [TVG] [INFO] Descargando configuración del cliente
[2022-06-15 04:47:05] [TVG] [INFO] Descargando perfil del servicio
[2022-06-15 04:47:05] [TVG] [INFO] Descargando parámetros de configuración
[2022-06-15 04:47:05] [TVG] [INFO] tvPackages: UTXC3|UTXC8|UTXFI
[2022-06-15 04:47:05] [TVG] [INFO] Demarcation: 12
[2022-06-15 04:47:05] [TVG] [INFO] Nuevos End Points: ['epNoCach1', 'epNoCach10', 'epNoCach11', 'epNoCach2', 'epNoCach3', 'epNoCach4', 'epNoCach5', 'epNoCach6', 'epNoCach7', 'epNoCach8', 'epNoCach9']
Traceback (most recent call last):
  File "C:\Users\jmarc\scoop\persist\python\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\Users\jmarc\scoop\persist\python\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "movistar_tvg.py", line 1438, in <module>
  File "C:\Users\jmarc\scoop\apps\python\current\lib\asyncio\runners.py", line 44, in run
  File "C:\Users\jmarc\scoop\apps\python\current\lib\asyncio\base_events.py", line 646, in run_until_complete
  File "movistar_tvg.py", line 1341, in tvg_main
  File "movistar_tvg.py", line 490, in get_service_config
KeyError: 'RES_BASE_URI'
[2022-06-15 04:47:08] [EPG] [ERROR] [2/3]...
[2022-06-15 04:47:08] [TVG] [INFO] -----------------------
[2022-06-15 04:47:08] [TVG] [INFO] Movistar U7D - TVG v5.1
[2022-06-15 04:47:08] [TVG] [INFO] -----------------------
[2022-06-15 04:47:08] [TVG] [INFO] Descargando configuración del cliente
[2022-06-15 04:47:08] [TVG] [INFO] Descargando perfil del servicio
[2022-06-15 04:47:08] [TVG] [INFO] Descargando parámetros de configuración
[2022-06-15 04:47:08] [TVG] [INFO] tvPackages: UTXC3|UTXC8|UTXFI
[2022-06-15 04:47:08] [TVG] [INFO] Demarcation: 12
[2022-06-15 04:47:08] [TVG] [INFO] Nuevos End Points: ['epNoCach1', 'epNoCach10', 'epNoCach11', 'epNoCach2', 'epNoCach3', 'epNoCach4', 'epNoCach5', 'epNoCach6', 'epNoCach7', 'epNoCach8', 'epNoCach9']
Traceback (most recent call last):
  File "C:\Users\jmarc\scoop\persist\python\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\Users\jmarc\scoop\persist\python\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "movistar_tvg.py", line 1438, in <module>
  File "C:\Users\jmarc\scoop\apps\python\current\lib\asyncio\runners.py", line 44, in run
  File "C:\Users\jmarc\scoop\apps\python\current\lib\asyncio\base_events.py", line 646, in run_until_complete
  File "movistar_tvg.py", line 1341, in tvg_main
  File "movistar_tvg.py", line 490, in get_service_config
KeyError: 'RES_BASE_URI'
[2022-06-15 04:47:11] [EPG] [ERROR] [3/3]...
[2022-06-15 04:47:12] [TVG] [INFO] -----------------------
[2022-06-15 04:47:12] [TVG] [INFO] Movistar U7D - TVG v5.1
[2022-06-15 04:47:12] [TVG] [INFO] -----------------------
[2022-06-15 04:47:12] [TVG] [INFO] Descargando configuración del cliente
[2022-06-15 04:47:12] [TVG] [INFO] Descargando perfil del servicio
[2022-06-15 04:47:12] [TVG] [INFO] Descargando parámetros de configuración
[2022-06-15 04:47:12] [TVG] [INFO] tvPackages: UTXC3|UTXC8|UTXFI
[2022-06-15 04:47:12] [TVG] [INFO] Demarcation: 12
[2022-06-15 04:47:12] [TVG] [INFO] Nuevos End Points: ['epNoCach1', 'epNoCach10', 'epNoCach11', 'epNoCach2', 'epNoCach3', 'epNoCach4', 'epNoCach5', 'epNoCach6', 'epNoCach7', 'epNoCach8', 'epNoCach9']
Traceback (most recent call last):
  File "C:\Users\jmarc\scoop\persist\python\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 113, in run
  File "C:\Users\jmarc\scoop\persist\python\Lib\site-packages\cx_Freeze\initscripts\Console.py", line 15, in run
  File "movistar_tvg.py", line 1438, in <module>
  File "C:\Users\jmarc\scoop\apps\python\current\lib\asyncio\runners.py", line 44, in run
  File "C:\Users\jmarc\scoop\apps\python\current\lib\asyncio\base_events.py", line 646, in run_until_complete
  File "movistar_tvg.py", line 1341, in tvg_main

**Comment by jmarcet** [comment]
Hola,

Gracias por avisar, no es problema tuyo sino que Movistar de repente ha cambiado en sus datos de programación `RES_BASE_URI` por ... no te lo vas a creer `res_BASE_URI`.

Ante lo absurdo del cambio lo he hecho un poco más robusto. Por suerte sólo afecta a quien lo usa por primera vez.

En cuanto pueda subo nueva versión para Windows.

**Comment by Lordpedal** [comment]
Buenas @jmarcet,

Buen y rápido parche que has añadido al script de Python, gran trabajo.

El repositorio del docker necesita de ser revisado también para que pueda aplicar la corrección.

Un saludo

**Comment by Juaancu08** [comment]
Osea,,, Simplemente cambian mayusculas por minusculas, vaya tontería. jajaja

**Comment by jmarcet** [comment]
Acabo de subir versión nueva. Han entrado algunas mejoras adicionales.

@Juaancu08 Sí, más tonto no podía ser y sin sentido. Para evitar sorpresas con nuevos cambios ahora funcionará con tal de que se llame algo parecido a `base uri`.

@Lordpedal Las imágenes de docker también están actualizadas.

Cualquier otro problema me avisáis :)
