### ISSUE TITLE
Instalación en debian...

### ISSUE THREAD

**Issue by vdias** [jmarcet/movistar-u7d#5]
Por favor revisar instalacion en debian... no funciona...

Imagino que hay que tocar la IP adaptando a la IP del servidor...
Imagino que hay que hacer un chmod +x para poder ejecutar...

Pero algo más falla...

```
 movistar_epg.service - Movistar U7D - EPG State service
     Loaded: loaded (/etc/systemd/system/movistar_epg.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Sun 2021-11-14 18:53:56 UTC; 3s ago
    Process: 7417 ExecStart=/usr/local/bin/movistar_epg.py (code=exited, status=1/FAILURE)
   Main PID: 7417 (code=exited, status=1/FAILURE)
        CPU: 382ms

Nov 14 18:53:56 MovistarTV movistar_epg.py[7417]:   File "/usr/lib/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
Nov 14 18:53:56 MovistarTV movistar_epg.py[7417]:     transport, protocol = await loop.subprocess_exec(
Nov 14 18:53:56 MovistarTV movistar_epg.py[7417]:   File "uvloop/loop.pyx", line 2793, in subprocess_exec
Nov 14 18:53:56 MovistarTV movistar_epg.py[7417]:   File "uvloop/loop.pyx", line 2751, in __subprocess_run
Nov 14 18:53:56 MovistarTV movistar_epg.py[7417]:   File "uvloop/handles/process.pyx", line 597, in uvloop.loop.UVProcessTransport.new
Nov 14 18:53:56 MovistarTV movistar_epg.py[7417]:   File "uvloop/handles/process.pyx", line 99, in uvloop.loop.UVProcess._init
Nov 14 18:53:56 MovistarTV movistar_epg.py[7417]: PermissionError: [Errno 13] Permission denied
Nov 14 18:53:56 MovistarTV movistar_epg.py[7417]: [2021-11-14 18:53:56] [7417] [CRITICAL] PermissionError(13, 'Permission denied')
Nov 14 18:53:56 MovistarTV systemd[1]: movistar_epg.service: Main process exited, code=exited, status=1/FAILURE
Nov 14 18:53:56 MovistarTV systemd[1]: movistar_epg.service: Failed with result 'exit-code'.
```

Se ejecuto el .py directamente... me saltan incluso mas errores...

```
root@MovistarTV:/# python3 /usr/local/bin/movistar_epg.py
[2021-11-14 19:17:58] [536] [INFO]
  ┌─────────────────────────────────────────────────────────────────────────────┐
  │                              Sanic v21.12.0dev                              │
  │                      Goin' Fast @ http://127.0.0.1:8889                     │
  ├───────────────────────┬─────────────────────────────────────────────────────┤
  │                       │     mode: production, single worker                 │
  │     ▄███ █████ ██     │   server: sanic                                     │
  │    ██                 │   python: 3.9.2                                     │
  │     ▀███████ ███▄     │ platform: Linux-5.11.22-5-pve-x86_64-with-glibc2.31 │
  │                 ██    │ packages: sanic-routing==0.7.2                      │
  │    ████ ████████▀     │                                                     │
  │                       │                                                     │
  │ Build Fast. Run Fast. │                                                     │
  └───────────────────────┴─────────────────────────────────────────────────────┘

[2021-11-14 19:17:58] [536] [WARNING] Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
[2021-11-14 19:17:58] [536] [WARNING] Missing channels data!. Need to download it. Please be patient...
[2021-11-14 19:17:58] [536] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1100, in run
    serve_single(server_settings)
  File "/usr/local/lib/python3.9/dist-packages/sanic/server/runners.py", line 199, in serve_single
    serve(**server_settings)
  File "/usr/local/lib/python3.9/dist-packages/sanic/server/runners.py", line 147, in serve
    loop.run_until_complete(app._server_event("init", "after"))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1650, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.9/dist-packages/sanic/signals.py", line 163, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.9/dist-packages/sanic/signals.py", line 133, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1426, in _listener
    await maybe_coro
  File "/usr/local/bin/movistar_epg.py", line 82, in after_server_start
    await reload_epg()
  File "/usr/local/bin/movistar_epg.py", line 415, in reload_epg
    await update_epg()
  File "/usr/local/bin/movistar_epg.py", line 712, in update_epg
    tvgrab = await asyncio.create_subprocess_exec(
  File "/usr/lib/python3.9/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "uvloop/loop.pyx", line 2793, in subprocess_exec
  File "uvloop/loop.pyx", line 2751, in __subprocess_run
  File "uvloop/handles/process.pyx", line 597, in uvloop.loop.UVProcessTransport.new
  File "uvloop/handles/process.pyx", line 99, in uvloop.loop.UVProcess._init
PermissionError: [Errno 13] Permission denied
[2021-11-14 19:17:58] [536] [CRITICAL] PermissionError(13, 'Permission denied')
root@MovistarTV:/#
```

**Comment by jmarcet** [comment]
`chmod` no debería ser necesario ninguno, tanto clonado con git como descargando un zip con todo el repo, los permisos deberían ser correctos.

La `LAN_IP` puede llegar a ser necesario, o deseable, ponerla manualmente.

De los logs intuyo que lo que no consigue ejecutar es el `tv_grab_es_movistartv`, que es ejecutado por `movistar_epg.py` para generar las listas de canales y la guía.

Asumo también que los permisos los has comprobado, lo único que se me ocurre es que no estén todos los `movistar_u7d.py`, `movistar_epg.py`, `tv_grab_es_movistartv` y `vod.py` en el `PATH`. Esto quiere decir que puedes ejecutarlos con sólo escribir su nombre, sin ninguna ruta. Un destino clásico que cumpla esto sería `/usr/local/bin`.

**Comment by vdias** [comment]
Me habia olvidado de una chmod... pero si hayq ue hacerlo si no, da error...

He tenido que hacer "chmod +x /usr/local/bin/..." de los 4 ficheros para que empiece a funcionar.

Pero pasado eso... algo sigue fallando...

```
root@MovistarTV:/# python3 /usr/local/bin/movistar_epg.py
[2021-11-14 19:29:32] [600] [INFO]
  ┌─────────────────────────────────────────────────────────────────────────────┐
  │                              Sanic v21.12.0dev                              │
  │                      Goin' Fast @ http://127.0.0.1:8889                     │
  ├───────────────────────┬─────────────────────────────────────────────────────┤
  │                       │     mode: production, single worker                 │
  │     ▄███ █████ ██     │   server: sanic                                     │
  │    ██                 │   python: 3.9.2                                     │
  │     ▀███████ ███▄     │ platform: Linux-5.11.22-5-pve-x86_64-with-glibc2.31 │
  │                 ██    │ packages: sanic-routing==0.7.2                      │
  │    ████ ████████▀     │                                                     │
  │                       │                                                     │
  │ Build Fast. Run Fast. │                                                     │
  └───────────────────────┴─────────────────────────────────────────────────────┘

[2021-11-14 19:29:32] [600] [WARNING] Sanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.
[2021-11-14 19:29:32] [600] [WARNING] Missing channels data!. Need to download it. Please be patient...
[2021-11-14 19:29:32] [600] [ERROR] Waiting 15s before trying to update EPG again [2/5]
[2021-11-14 19:29:48] [600] [ERROR] Waiting 15s before trying to update EPG again [3/5]
[2021-11-14 19:30:03] [600] [ERROR] Waiting 15s before trying to update EPG again [4/5]
[2021-11-14 19:30:18] [600] [ERROR] Waiting 15s before trying to update EPG again [5/5]
[2021-11-14 19:30:34] [600] [ERROR] Waiting 15s before trying to update EPG again [6/5]
[2021-11-14 19:30:49] [600] [ERROR] Failed to load EPG data FileNotFoundError(2, 'No such file or directory')
[2021-11-14 19:30:49] [600] [WARNING] Missing channels data!. Need to download it. Please be patient...
[2021-11-14 19:30:49] [600] [ERROR] Waiting 15s before trying to update EPG again [2/5]
[2021-11-14 19:31:04] [600] [ERROR] Waiting 15s before trying to update EPG again [3/5]
[2021-11-14 19:31:20] [600] [ERROR] Waiting 15s before trying to update EPG again [4/5]
[2021-11-14 19:31:35] [600] [ERROR] Waiting 15s before trying to update EPG again [5/5]
[2021-11-14 19:31:51] [600] [ERROR] Waiting 15s before trying to update EPG again [6/5]
[2021-11-14 19:32:06] [600] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/local/bin/movistar_epg.py", line 419, in reload_epg
    async with await open_async(epg_data) as f:
  File "/usr/local/lib/python3.9/dist-packages/aiofiles/base.py", line 75, in __aenter__
    self._obj = await self._coro
  File "/usr/local/lib/python3.9/dist-packages/aiofiles/threadpool/__init__.py", line 80, in _open
    f = yield from loop.run_in_executor(executor, cb)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.xmltv/cache/epg.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1100, in run
    serve_single(server_settings)
  File "/usr/local/lib/python3.9/dist-packages/sanic/server/runners.py", line 199, in serve_single
    serve(**server_settings)
  File "/usr/local/lib/python3.9/dist-packages/sanic/server/runners.py", line 147, in serve
    loop.run_until_complete(app._server_event("init", "after"))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1650, in _server_event
    await self.dispatch(
  File "/usr/local/lib/python3.9/dist-packages/sanic/signals.py", line 163, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.9/dist-packages/sanic/signals.py", line 133, in _dispatch
    retval = await maybe_coroutine
  File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1426, in _listener
    await maybe_coro
  File "/usr/local/bin/movistar_epg.py", line 82, in after_server_start
    await reload_epg()
  File "/usr/local/bin/movistar_epg.py", line 432, in reload_epg
    return await reload_epg()
  File "/usr/lib/python3.9/asyncio/locks.py", line 120, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-4' coro=<Sanic._server_event() running at /usr/local/lib/python3.9/dist-packages/sanic/app.py:1650> cb=[run_until_complete.<locals>.done_cb()]> got Future <Future pending> attached to a different loop
[2021-11-14 19:32:06] [600] [CRITICAL] RuntimeError("Task <Task pending name='Task-4' coro=<Sanic._server_event() running at /usr/local/lib/python3.9/dist-packages/sanic/app.py:1650> cb=[run_until_complete.<locals>.done_cb()]> got Future <Future pending> attached to a different loop")
```

**Comment by vdias** [comment]
> `chmod` no debería ser necesario ninguno, tanto clonado con git como descargando un zip con todo el repo, los permisos deberían ser correctos.
> 
> La `LAN_IP` puede llegar a ser necesario, o deseable, ponerla manualmente.
> 
> De los logs intuyo que lo que no consigue ejecutar es el `tv_grab_es_movistartv`, que es ejecutado por `movistar_epg.py` para generar las listas de canales y la guía.
> 
> Asumo también que los permisos los has comprobado, lo único que se me ocurre es que no estén todos los `movistar_u7d.py`, `movistar_epg.py`, `tv_grab_es_movistartv` y `vod.py` en el `PATH`. Esto quiere decir que puedes ejecutarlos con sólo escribir su nombre, sin ninguna ruta. Un destino clásico que cumpla esto sería `/usr/local/bin`.
> 
> Aún así asegúrate de que los 4 tengan permisos de ejecución, de serie deberían estar así:
> 
> ```
> ❯ la
> total 240K
> -rw-rw-r-- 1 jmarcet jmarcet    9 Nov 14 20:31 .dockerignore
> drwxrwxr-x 1 jmarcet jmarcet  138 Nov 14 20:31 .git/
> -rw-rw-r-- 1 jmarcet jmarcet   20 Nov 14 20:31 .gitignore
> -rw-rw-r-- 1 jmarcet jmarcet  606 Nov 14 20:31 .gitlab-ci.yml
> -rw-rw-r-- 1 jmarcet jmarcet  596 Nov 14 20:31 Dockerfile
> -rw-rw-r-- 1 jmarcet jmarcet  18K Nov 14 20:31 LICENSE
> -rw-rw-r-- 1 jmarcet jmarcet  35K Nov 14 20:31 README.md
> -rw-rw-r-- 1 jmarcet jmarcet 1.1K Nov 14 20:31 docker-compose.yml
> -rw-rw-r-- 1 jmarcet jmarcet 1.1K Nov 14 20:31 env-example
> -rw-rw-r-- 1 jmarcet jmarcet 5.0K Nov 14 20:31 grafana-dashboard.json
> -rwxrwxr-x 1 jmarcet jmarcet  181 Nov 14 20:31 health.sh
> -rwxrwxr-x 1 jmarcet jmarcet  29K Nov 14 20:31 movistar_epg.py
> -rw-rw-r-- 1 jmarcet jmarcet  381 Nov 14 20:31 movistar_epg.service
> -rwxrwxr-x 1 jmarcet jmarcet  19K Nov 14 20:31 movistar_u7d.py
> -rw-rw-r-- 1 jmarcet jmarcet  407 Nov 14 20:31 movistar_u7d.service
> -rw-rw-r-- 1 jmarcet jmarcet  132 Nov 14 20:31 requirements.txt
> -rwxrwxr-x 1 jmarcet jmarcet  453 Nov 14 20:31 start.sh
> -rw-rw-r-- 1 jmarcet jmarcet  940 Nov 14 20:31 timers.conf
> -rw-rw-r-- 1 jmarcet jmarcet  160 Nov 14 20:31 tox.ini
> -rwxrwxr-x 1 jmarcet jmarcet  55K Nov 14 20:31 tv_grab_es_movistartv
> -rwxrwxr-x 1 jmarcet jmarcet  16K Nov 14 20:31 vod.py
> ```

No tengo tantos ficheros, solo los 4 que comentas en el guia de instalacion...

**Comment by jmarcet** [comment]
No entiendo por qué necesitas los `chmod`. Antes de escribirte me aseguré y comprobé las dos formas de descarga, de ambas maneras me queda todo con los permisos correctos, tal como ves arriba.

El problema es que no consigue descargar nada de la IPTV de Movistar.

Estás seguro de que tienes conectividad con ella?

Qué te sale al ejecutar:

```
dig @172.26.23.3 telefonica.net
```

**Comment by vdias** [comment]
```
root@MovistarTV:/# dig @172.26.23.3 telefonica.net

; <<>> DiG 9.16.22-Debian <<>> @172.26.23.3 telefonica.net
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62023
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;telefonica.net.                        IN      A

;; AUTHORITY SECTION:
telefonica.net.         60      IN      SOA     dns2.movistar.es. admondns.tsm.es. 2017050574 10800 3600 2419200 900

;; Query time: 20 msec
;; SERVER: 172.26.23.3#53(172.26.23.3)
;; WHEN: Sun Nov 14 19:38:33 UTC 2021
;; MSG SIZE  rcvd: 108

root@MovistarTV:/#
```

**Comment by jmarcet** [comment]
Bien, conectividad, al menos a las DNS tienes.

Pues prueba a ejecutar el `tv_grab_es_movistartv` por separado, ahí está el problema.

Para generar la lista de canales:
```
tv_grab_es_movistartv --m3u /home/MovistarTV.m3u
```

Para generar la lista de canales y la guía:
```
tv_grab_es_movistartv --tvheadend /home/MovistarTV.m3u --output /home/guide.xml
````

**Comment by vdias** [comment]
```
root@MovistarTV:/# ./usr/local/bin/tv_grab_es_movistartv --tvheadend /MovistarTV/MovistarTV.m3u --output /MovistarTV/guide.xml
root@MovistarTV:/# ls -la /MovistarTV/
total 8
drwxr-xr-x  2 root root 4096 Nov 14 19:23 .
drwxr-xr-x 28 root root 4096 Nov 14 19:23 ..
root@MovistarTV:/#
```

**Comment by jmarcet** [comment]
Toda esta información llega como los canales en directo, por multicast, que también es imprescindible que te llegue al equipo.

Eso que me pegas arriba no tiene sentido, quiero decir, no has hecho nada en el primer paso, no da ningún tipo de salida ni error. no sé debido a qué pero no se está ejecutando.

**Comment by jmarcet** [comment]
¿Te funciona ya?

**Comment by vdias** [comment]
Que va... sigue igual... he desplegado de nuevo el CT de Proxmox por si acaso, pero sigue igual...

**Comment by jmarcet** [comment]
Qué versión de Python estás usando? No le veo sentido a esos logs.

**Comment by vdias** [comment]
Python 3.9.2

**Comment by jmarcet** [comment]
Pues no entiendo qué está fallando.

Sólo te puedo pedir que le quites el `try/catch del final` para tener una mejor idea de dónde da el error ese del `msg`.

Tendrías que borrar:
```
except Exception as ex:
logger.critical(f"{repr(ex)}")
sys.exit(1)
```

y el:
```
try:
```
de la línea 1354, después borrar el sangrado de las líneas entre ambos, de manera que queden alineadas a la primera columna.

Hechos esos cambios, si lo ejecutas de nuevo, podremos tener una mejor idea de dónde exactamente está dando el error.

**Comment by vdias** [comment]
¿Eliminar todo lo que viene despues de la linea 1354?

**Comment by jmarcet** [comment]
Como [aquí](https://github.com/jmarcet/movistar-u7d/blob/debug/tv_grab_es_movistartv)

He subido una nueva rama, [debug](https://github.com/jmarcet/movistar-u7d/tree/debug) con el `tv_grab_es_movistartv` modificado como te digo.

**Comment by vdias** [comment]
```
root@MovistarTV:~# tv_grab_es_movistartv --tvheadend /MovistarTV/MovistarTV.m3u --output /MovistarTV/guide.xml
Traceback (most recent call last):
  File "/usr/local/bin/tv_grab_es_movistartv", line 1371, in <module>
    config = mtv.get_service_config()
  File "/usr/local/bin/tv_grab_es_movistartv", line 536, in get_service_config
    cfg = cache.load_config()
  File "/usr/local/bin/tv_grab_es_movistartv", line 401, in load_config
    logger.warning()("Caché: configuración no encontrada")
TypeError: warning() missing 1 required positional argument: 'msg'
root@MovistarTV:~#
```

**Comment by jmarcet** [comment]
Wow, no sé desde cuándo está esa línea así, has encontrado un buen error cuando intenta escribir ese mensaje de `configuración no encontrada`. Dame un momento y lo subo arreglado, pero puedes ir probando. Si te fijas la palabra `warning` 
 de la línea 401 va seguida de unos `()` vacíos, seguido de otros con el mensaje, pues hay que borrar los paréntesis vacíos:

```
logger.warning("Caché: configuración no encontrada")
```

**Comment by jmarcet** [comment]
He subido ya el arreglo.

¿Te funciona ahora?

**Comment by vdias** [comment]
que va... esto sigue sin descargar...

**Comment by jmarcet** [comment]
Pero hará otra cosa. Estaba rompiendo por una tontería al no tener ninguna caché previa. es decir, al ejecutarlo por primera vez.

Como mínimo te debe dar otro error. Puedes actualizarlo, descargarlo de nuevo, como prefieras.

**Comment by jmarcet** [comment]
Déjame ejecutarlo en mi portátil, hace tiempo que no lo arranco vacío del todo, o sea, como recién instalado.

**Comment by jmarcet** [comment]
Puedes descargarlo de nuevo y probar otra vez? Aún estoy descargando la guía completa (sin caché de ningún tipo) pero he arreglado otros dos errores y parece estar funcionando bien ahora.

**Comment by vdias** [comment]
Sigo con problemas...

```
[2021-11-15 20:49:16] [INFO] ---------------------------------------------------
[2021-11-15 20:49:16] [INFO] MovistarTV EPG Grabber
[2021-11-15 20:49:16] [INFO] Parámetros: ['--tvheadend', '/MovistarTV/MovistarTV.m3u', '--output', '/MovistarTV/guide.xml']
[2021-11-15 20:49:16] [INFO] ---------------------------------------------------
[2021-11-15 20:49:16] [INFO] Descargando configuración del cliente
[2021-11-15 20:49:16] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 3
[2021-11-15 20:49:16] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 2
[2021-11-15 20:49:16] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 1
[2021-11-15 20:49:16] [WARNING] Timeout: http://www-60.svc.imagenio.telefonica.net:2001, reintentos: 0
[2021-11-15 20:49:16] [ERROR] End Point http://www-60.svc.imagenio.telefonica.net:2001 desactivado
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 3
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 2
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 1
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc2.svc.imagenio.telefonica.net:2001, reintentos: 0
[2021-11-15 20:49:16] [ERROR] End Point http://nc2.svc.imagenio.telefonica.net:2001 desactivado
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 3
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 2
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 1
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc4.svc.imagenio.telefonica.net:2001, reintentos: 0
[2021-11-15 20:49:16] [ERROR] End Point http://nc4.svc.imagenio.telefonica.net:2001 desactivado
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 3
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 2
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 1
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc5.svc.imagenio.telefonica.net:2001, reintentos: 0
[2021-11-15 20:49:16] [ERROR] End Point http://nc5.svc.imagenio.telefonica.net:2001 desactivado
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 3
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 2
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 1
[2021-11-15 20:49:16] [WARNING] Timeout: http://nc6.svc.imagenio.telefonica.net:2001, reintentos: 0
[2021-11-15 20:49:16] [ERROR] End Point http://nc6.svc.imagenio.telefonica.net:2001 desactivado
[2021-11-15 20:49:16] [ERROR] Servicio Web de Movistar TV caído: decargando guía básica
[2021-11-15 20:49:16] [ERROR] __get_client_profile: TypeError("'NoneType' object is not subscriptable")
[2021-11-15 20:49:16] [ERROR] Usando la configuración de cliente por defecto: 24|ALL|1
[2021-11-15 20:49:16] [INFO] Descargando perfil del servicio
[2021-11-15 20:49:16] [ERROR] __get_platform_profile: TypeError("'NoneType' object is not subscriptable")
[2021-11-15 20:49:16] [ERROR] Usando el perfil del servicio por defecto
[2021-11-15 20:49:16] [INFO] Descargando parámetros de configuración
[2021-11-15 20:49:16] [ERROR] __get_config_params: TypeError("'NoneType' object is not subscriptable")
[2021-11-15 20:49:16] [ERROR] Usando los parámetros de configuración por defecto
```

**Comment by jmarcet** [comment]
Hola,

Eso es porque tienes un problema con el tráfico multicast, no parece llegarle al equipo en cuestión.

Si usas el router de Movistar, el equipo tiene que estar conectado por cable. Si es un router diferente, puedes hacerlo funcionar por wifi con el igmpproxy.

Fuera de eso, no sé qué problema tienes. Te remito al [Foro Movistar de BandaAncha](https://bandaancha.eu/foros/movistar), y como mucho que pruebes a ajustar la variable de entorno `EPG_THREADS` con un número bajo, pero no tiene pinta de eso sino que de no te llega en absoluto el multicast de la VLAN 2 de Movistar.

**Comment by vdias** [comment]
Raro, porque en el equipo que está en la misma VLAN de las virtuales, si tengo acceso al Multicast... reviso tema Proxmox. Gracias
