### ISSUE TITLE
Error en los microservicios Sanic

### ISSUE THREAD

**Issue by jagbarcelo** [jmarcet/movistar-u7d#9]
Estoy tratando de poner en marcha tu proyecto en una Raspberry Pi 4 con Ubuntu Server 20.10 de 64bits.

Mi pasos:
* Instalación limpia y actualizada.
* Configuro una IP estática (en lugar de usar dhcp)
* Instalo `ffmpeg`, `mkvtoolnix` y `python3-pip`
* Clono tu repositorio con `git clone ...`
* Instalo las dependencias con `pip3 install -r requirements.txt`
* Copio los ficheros indicados `.py` a la ruta `usr/local/bin/`
* Copio y edito los ficheros `.service` a la ruta `/etc/systemd/system/`
  * En las ediciones, habilito las líneas de Environment para HOME, LAN_IP y SANIC_PORT, el resto se dejan comentadas
* Configuro y arranco los servicios con `systemctl enable ...` y `systemctl start ...`

Si abro el fichero `/var/log/syslog`, al final del mismo aparecen los mensajes siguientes:

```
[...]
Jan  5 10:39:03 pi-u7d systemd[1]: Started Movistar U7D - EPG State service.
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: [2022-01-05 10:39:04] [2414] [INFO] Sanic v21.12.0
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: [2022-01-05 10:39:04] [2414] [INFO] Goin' Fast @ http://127.0.0.1:8889
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: [2022-01-05 10:39:04] [2414] [INFO] mode: production, single worker
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: [2022-01-05 10:39:04] [2414] [INFO] server: sanic
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: [2022-01-05 10:39:04] [2414] [INFO] python: 3.9.7
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: [2022-01-05 10:39:04] [2414] [INFO] platform: Linux-5.13.0-1012-raspi-aarch64-with-glibc2.34
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: [2022-01-05 10:39:04] [2414] [INFO] packages: sanic-routing==0.7.2
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: [2022-01-05 10:39:04] [2414] [ERROR] Experienced exception while trying to serve
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: Traceback (most recent call last):
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "/usr/local/lib/python3.9/dist-packages/sanic/base/root.py", line 56, in __setattr__
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:     super().__setattr__(name, value)
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: AttributeError: 'Sanic' object has no attribute 'metrics'
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: The above exception was the direct cause of the following exception:
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: Traceback (most recent call last):
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1204, in run
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:     serve_single(server_settings)
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "/usr/local/lib/python3.9/dist-packages/sanic/server/runners.py", line 206, in serve_single
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:     serve(**server_settings)
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "/usr/local/lib/python3.9/dist-packages/sanic/server/runners.py", line 130, in serve
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:     loop.run_until_complete(app._server_event("init", "before"))
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1980, in _server_event
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:     await self.dispatch(
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "/usr/local/lib/python3.9/dist-packages/sanic/signals.py", line 191, in dispatch
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:     return await dispatch
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "/usr/local/lib/python3.9/dist-packages/sanic/signals.py", line 161, in _dispatch
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:     retval = await maybe_coroutine
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "/usr/local/lib/python3.9/dist-packages/sanic/app.py", line 1522, in _listener
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:     maybe_coro = listener(app, loop)
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "/usr/local/lib/python3.9/dist-packages/sanic_prometheus/__init__.py", line 108, in before_start
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:     app.metrics = {}
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:   File "/usr/local/lib/python3.9/dist-packages/sanic/base/root.py", line 58, in __setattr__
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]:     raise AttributeError(
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: AttributeError: Setting variables on Sanic instances is not allowed. You should change your Sanic instance to use instance.ctx.metrics instead.
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: [2022-01-05 10:39:04] [2414] [CRITICAL] AttributeError('Setting variables on Sanic instances is not allowed. You should change your Sanic instance to use instance.ctx.metrics instead.')
Jan  5 10:39:04 pi-u7d movistar_epg.py[2414]: sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
Jan  5 10:39:04 pi-u7d systemd[1]: movistar_epg.service: Main process exited, code=exited, status=1/FAILURE
Jan  5 10:39:04 pi-u7d systemd[1]: movistar_epg.service: Failed with result 'exit-code'.
Jan  5 10:39:04 pi-u7d systemd[1]: movistar_epg.service: Consumed 1.602s CPU time.
```

Si ejecuto manualmente `tv_grab_es_movistartv --tvheadend /home/MovistarTV.m3u --output /home/guide.xml` se generan los ficheros correctamente. Aparentemente sólo está fallando la parte en la que se instalan como servicios.

Alguna idea?

**Comment by jmarcet** [comment]
Hola,

He visto el error trasteando con python en Windows. El origen son las métricas prometheus, aunque no tengo claro aún el por qué.

Puedes evitarlo quitando las líneas [778](https://github.com/jmarcet/movistar-u7d/blob/cbf7e196c8f10203797b0d65ba6a1b048432b2ca/movistar_epg.py#L778) a [784](https://github.com/jmarcet/movistar-u7d/blob/cbf7e196c8f10203797b0d65ba6a1b048432b2ca/movistar_epg.py#L784).

No resultan esenciales en absoluto para que funcione el proxy, sólo para tener gráficas en un Grafana.

Como alternativa, te diría que usases la versión en docker, no te va a rendir peor y lo tendrás todo contenido.

**Comment by jmarcet** [comment]
He acabando por forkear [sanic-prometheus](https://github.com/jmarcet/sanic-prometheus) para arreglar el problema de compatibilidad con el último Sanic.

Si actualizas el repo y vuelves a instalar todo con pip, te debería funcionar correctamente.
